from city_scrapers_core.constants import (
    BOARD,
    CITY_COUNCIL,
    COMMISSION,
    COMMITTEE,
    NOT_CLASSIFIED,
)

from city_scrapers.mixins.kancit_missouricity import KancitMissouricityMixin

# Configuration for each spider - 199 bodies from Kansas City calendar dropdown
# Source: https://clerk.kcmo.gov/Calendar.aspx (committee filter dropdown)
spider_configs = [
    {
        "class_name": "KancitSpider001",
        "name": "kancit_1200_main_south_loop_community_improvement",
        "agency": "1200 Main South Loop Community Improvement District",
        "agency_filter": "1200 Main South Loop Community Improvement District",
        "classification": NOT_CLASSIFIED,
        "meeting_location": {
            "name": "26th Floor, Council Chamber",
            "address": "414 E. 12th Street, Kansas City, MO 64106",
        },
    },
    {
        "class_name": "KancitSpider002",
        "name": "kancit_002",
        "agency": "18th and Vine Development Policy Committee",
        "agency_filter": "18th and Vine Development Policy Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider003",
        "name": "kancit_003",
        "agency": "Air Quality Appeals Board",
        "agency_filter": "Air Quality Appeals Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider004",
        "name": "kancit_004",
        "agency": "Airport Committee",
        "agency_filter": "Airport Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider005",
        "name": "kancit_005",
        "agency": "Alcohol Beverage Advisory Board",
        "agency_filter": "Alcohol Beverage Advisory Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider006",
        "name": "kancit_006",
        "agency": "Alternatives to Incarceration Commission",
        "agency_filter": "Alternatives to Incarceration Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider007",
        "name": "kancit_007",
        "agency": "Architect and Engineering Selection Committee",
        "agency_filter": "Architect and Engineering Selection Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider008",
        "name": "kancit_008",
        "agency": "Arterial Impact Fee Committee - District G",
        "agency_filter": "Arterial Impact Fee Committee - District G",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider009",
        "name": "kancit_009",
        "agency": "Arterial Street Impact Fee Airport District A",
        "agency_filter": "Arterial Street Impact Fee Airport District A",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider010",
        "name": "kancit_010",
        "agency": "Arterial Street Impact Line Creek District E",
        "agency_filter": "Arterial Street Impact Line Creek District E",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider011",
        "name": "kancit_011",
        "agency": "Bicycle and Pedestrian Advisory Committee",
        "agency_filter": "Bicycle and Pedestrian Advisory Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider012",
        "name": "kancit_012",
        "agency": "Board of Police Commissioners",
        "agency_filter": "Board of Police Commissioners",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider013",
        "name": "kancit_013",
        "agency": "Board of Trustees of City Trusts",
        "agency_filter": "Board of Trustees of City Trusts",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider014",
        "name": "kancit_014",
        "agency": "Board of Zoning Adjustment",
        "agency_filter": "Board of Zoning Adjustment",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider015",
        "name": "kancit_015",
        "agency": "Bond Financial Advisory Committee",
        "agency_filter": "Bond Financial Advisory Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider016",
        "name": "kancit_016",
        "agency": "Brownfields Commission",
        "agency_filter": "Brownfields Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider017",
        "name": "kancit_017",
        "agency": "Budget and Audit Committee",
        "agency_filter": "Budget and Audit Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider018",
        "name": "kancit_018",
        "agency": "Business Session",
        "agency_filter": "Business Session",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider019",
        "name": "kancit_019",
        "agency": "Candidate Forum Meeting(s)",
        "agency_filter": "Candidate Forum Meeting(s)",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider020",
        "name": "kancit_central_city_economic_development_sales",
        "agency": "Central City Economic Development Sales Tax Board",
        "agency_filter": "Central City Economic Development Sales Tax Board",
        "classification": BOARD,
        "meeting_location": {
            "name": "26th Floor, Council Chamber",
            "address": "414 E. 12th Street, Kansas City, MO 64106",
        },
    },
    {
        "class_name": "KancitSpider021",
        "name": "kancit_021",
        "agency": "Charter Review Commission",
        "agency_filter": "Charter Review Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider022",
        "name": "kancit_022",
        "agency": "Citizen's Commission on Municipal Revenue",
        "agency_filter": "Citizen's Commission on Municipal Revenue",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider023",
        "name": "kancit_023",
        "agency": "City Clerk",
        "agency_filter": "City Clerk",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider024",
        "name": "kancit_024",
        "agency": "City Council Business Session",
        "agency_filter": "City Council Business Session",
        "classification": CITY_COUNCIL,
    },
    {
        "class_name": "KancitSpider025",
        "name": "kancit_025",
        "agency": "City Market Oversight Committee",
        "agency_filter": "City Market Oversight Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider026",
        "name": "kancit_026",
        "agency": "City Operations Committee",
        "agency_filter": "City Operations Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider027",
        "name": "kancit_027",
        "agency": "City Plan Commission",
        "agency_filter": "City Plan Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider028",
        "name": "kancit_028",
        "agency": "City's Risk Management Committee's Claims Subcommittee",
        "agency_filter": "City's Risk Management Committee's Claims Subcommittee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider029",
        "name": "kancit_029",
        "agency": "Civil Rights and Equal Opportunity (CREO) Department",
        "agency_filter": "Civil Rights and Equal Opportunity (CREO) Department",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider030",
        "name": "kancit_030",
        "agency": "Community Engagement",
        "agency_filter": "Community Engagement",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider031",
        "name": "kancit_031",
        "agency": "Construction Workforce Board",
        "agency_filter": "Construction Workforce Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider032",
        "name": "kancit_032",
        "agency": "Convention Hotel Steering Committee",
        "agency_filter": "Convention Hotel Steering Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider033",
        "name": "kancit_033",
        "agency": "Convention Management Advisory Authority",
        "agency_filter": "Convention Management Advisory Authority",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider034",
        "name": "kancit_council",
        "agency": "Council",
        "agency_filter": "Council",
        "classification": CITY_COUNCIL,
        "meeting_location": {
            "name": "26th Floor, Council Chamber",
            "address": "414 E. 12th Street, Kansas City, MO 64106",
        },
    },
    {
        "class_name": "KancitSpider035",
        "name": "kancit_035",
        "agency": "Crossroads Arts Advisory Committee PIEA",
        "agency_filter": "Crossroads Arts Advisory Committee PIEA",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider036",
        "name": "kancit_036",
        "agency": "Crossroads Community Improvement District",
        "agency_filter": "Crossroads Community Improvement District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider037",
        "name": "kancit_037",
        "agency": "Deferred Compensation Plan Board",
        "agency_filter": "Deferred Compensation Plan Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider038",
        "name": "kancit_038",
        "agency": "Dog Park Master Plan Task Force",
        "agency_filter": "Dog Park Master Plan Task Force",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider039",
        "name": "kancit_039",
        "agency": "Downtown Economic Stimulus Authority",
        "agency_filter": "Downtown Economic Stimulus Authority",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider040",
        "name": "kancit_040",
        "agency": "Downtown Transportation Development District (TDD)",
        "agency_filter": "Downtown Transportation Development District (TDD)",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider041",
        "name": "kancit_041",
        "agency": "Economic Development Committee",
        "agency_filter": "Economic Development Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider042",
        "name": "kancit_042",
        "agency": "Economic Development Corporation",
        "agency_filter": "Economic Development Corporation",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider043",
        "name": "kancit_043",
        "agency": "Economic Development Corporation Board of Directors",
        "agency_filter": "Economic Development Corporation Board of Directors",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider044",
        "name": "kancit_044",
        "agency": "Emergency Medical Services Coordinating Committee",
        "agency_filter": "Emergency Medical Services Coordinating Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider045",
        "name": "kancit_045",
        "agency": "Emergency Medical Services Coordination Committee (EMSCC)",
        "agency_filter": "Emergency Medical Services Coordination Committee (EMSCC)",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider046",
        "name": "kancit_046",
        "agency": "Emerging Technology Board",
        "agency_filter": "Emerging Technology Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider047",
        "name": "kancit_047",
        "agency": "Employee Retirement System Board of Trustees",
        "agency_filter": "Employee Retirement System Board of Trustees",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider048",
        "name": "kancit_048",
        "agency": "Employees Retirement System Board of Trustees",
        "agency_filter": "Employees Retirement System Board of Trustees",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider049",
        "name": "kancit_049",
        "agency": "Environmental Management Commission",
        "agency_filter": "Environmental Management Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider050",
        "name": "kancit_050",
        "agency": "EPA Response Team",
        "agency_filter": "EPA Response Team",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider051",
        "name": "kancit_051",
        "agency": "Equity Task Force",
        "agency_filter": "Equity Task Force",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider052",
        "name": "kancit_052",
        "agency": "Ethics and Legal Review Committee",
        "agency_filter": "Ethics and Legal Review Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider053",
        "name": "kancit_053",
        "agency": "F & G and T & I Joint Committee",
        "agency_filter": "F & G and T & I Joint Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider054",
        "name": "kancit_054",
        "agency": "Fairness in Construction Board",
        "agency_filter": "Fairness in Construction Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider055",
        "name": "kancit_055",
        "agency": "Fairness In Professional Goods & Services Board",
        "agency_filter": "Fairness In Professional Goods & Services Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider056",
        "name": "kancit_056",
        "agency": "Finance & Administration Committee",
        "agency_filter": "Finance & Administration Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider057",
        "name": "kancit_057",
        "agency": "Finance and Audit Committee",
        "agency_filter": "Finance and Audit Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider058",
        "name": "kancit_058",
        "agency": "Finance and Governance Committee",
        "agency_filter": "Finance and Governance Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider059",
        "name": "kancit_059",
        "agency": "Finance Governance &  Ethics  Work Session",
        "agency_filter": "Finance Governance &  Ethics  Work Session",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider060",
        "name": "kancit_060",
        "agency": "Finance, Governance & Ethics Committee",
        "agency_filter": "Finance, Governance & Ethics Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider061",
        "name": "kancit_061",
        "agency": "Finance, Governance & Neighborhoods Joint Committee",
        "agency_filter": "Finance, Governance & Neighborhoods Joint Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider062",
        "name": "kancit_062",
        "agency": "Finance, Governance and Ethics Committee and Public Safety and Emergency Services Committee",
        "agency_filter": "Finance, Governance and Ethics Committee and Public Safety and Emergency Services Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider063",
        "name": "kancit_063",
        "agency": "Finance, Governance and Public Safety Committee",
        "agency_filter": "Finance, Governance and Public Safety Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider064",
        "name": "kancit_064",
        "agency": "Firefighters Pension System Board of Trustees",
        "agency_filter": "Firefighters Pension System Board of Trustees",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider065",
        "name": "kancit_065",
        "agency": "Focused Deterrence Governing Board",
        "agency_filter": "Focused Deterrence Governing Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider066",
        "name": "kancit_066",
        "agency": "Health Commission",
        "agency_filter": "Health Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider067",
        "name": "kancit_067",
        "agency": "Health Foward Foundation - Community Advisory Committee",
        "agency_filter": "Health Foward Foundation - Community Advisory Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider068",
        "name": "kancit_068",
        "agency": "Healthcare System Board of Trustees",
        "agency_filter": "Healthcare System Board of Trustees",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider069",
        "name": "kancit_069",
        "agency": "Historic Preservation Commission",
        "agency_filter": "Historic Preservation Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider070",
        "name": "kancit_070",
        "agency": "HomelessTask Force",
        "agency_filter": "HomelessTask Force",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider071",
        "name": "kancit_071",
        "agency": "Homesteading Authority",
        "agency_filter": "Homesteading Authority",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider072",
        "name": "kancit_072",
        "agency": "Houseless Taskforce",
        "agency_filter": "Houseless Taskforce",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider073",
        "name": "kancit_073",
        "agency": "Housing & Community Development Committee",
        "agency_filter": "Housing & Community Development Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider074",
        "name": "kancit_074",
        "agency": "Housing and Planning, Zoning & Economic Development Committee",
        "agency_filter": "Housing and Planning, Zoning & Economic Development Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider075",
        "name": "kancit_075",
        "agency": "Housing Authority",
        "agency_filter": "Housing Authority",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider076",
        "name": "kancit_076",
        "agency": "Housing Committee",
        "agency_filter": "Housing Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider077",
        "name": "kancit_077",
        "agency": "Housing Committee Worksession",
        "agency_filter": "Housing Committee Worksession",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider078",
        "name": "kancit_078",
        "agency": "Housing Trust Fund Board",
        "agency_filter": "Housing Trust Fund Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider079",
        "name": "kancit_079",
        "agency": "Human Relations",
        "agency_filter": "Human Relations",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider080",
        "name": "kancit_080",
        "agency": "Human Rights Commission",
        "agency_filter": "Human Rights Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider081",
        "name": "kancit_081",
        "agency": "Independence Avenue Special Design Review Districts",
        "agency_filter": "Independence Avenue Special Design Review Districts",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider082",
        "name": "kancit_082",
        "agency": "International Committee",
        "agency_filter": "International Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider083",
        "name": "kancit_083",
        "agency": "International Energy Conservation Code",
        "agency_filter": "International Energy Conservation Code",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider084",
        "name": "kancit_084",
        "agency": "Investment Committee",
        "agency_filter": "Investment Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider085",
        "name": "kancit_085",
        "agency": "Jackson County Board of Equalization",
        "agency_filter": "Jackson County Board of Equalization",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider086",
        "name": "kancit_086",
        "agency": "Jazz District Redevelopment Corp.",
        "agency_filter": "Jazz District Redevelopment Corp.",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider087",
        "name": "kancit_087",
        "agency": "Joint Committee of Finance and Special Committee on Housing Policy",
        "agency_filter": "Joint Committee of Finance and Special Committee on Housing Policy",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider088",
        "name": "kancit_088",
        "agency": "Kansas City Board of Election Commissioners",
        "agency_filter": "Kansas City Board of Election Commissioners",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider089",
        "name": "kancit_089",
        "agency": "Kansas City Climate Protection Plan Steering Committee",
        "agency_filter": "Kansas City Climate Protection Plan Steering Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider090",
        "name": "kancit_090",
        "agency": "Kansas City Climate Protection Steering Committee",
        "agency_filter": "Kansas City Climate Protection Steering Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider091",
        "name": "kancit_091",
        "agency": "Kansas City Commission on Violent Crime",
        "agency_filter": "Kansas City Commission on Violent Crime",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider092",
        "name": "kancit_092",
        "agency": "Kansas City COVID-19 Vaccine Task Force",
        "agency_filter": "Kansas City COVID-19 Vaccine Task Force",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider093",
        "name": "kancit_093",
        "agency": "Kansas City Maintenance Reserve Corporation",
        "agency_filter": "Kansas City Maintenance Reserve Corporation",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider094",
        "name": "kancit_094",
        "agency": "Kansas City Missouri Parking and Transportation Commission",
        "agency_filter": "Kansas City Missouri Parking and Transportation Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider095",
        "name": "kancit_095",
        "agency": "Kansas City Museum Foundation Board",
        "agency_filter": "Kansas City Museum Foundation Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider096",
        "name": "kancit_096",
        "agency": "Kansas City Redistricting Commission",
        "agency_filter": "Kansas City Redistricting Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider097",
        "name": "kancit_097",
        "agency": "Kansas City Streetcar Authority",
        "agency_filter": "Kansas City Streetcar Authority",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider098",
        "name": "kancit_098",
        "agency": "Kansas City Workers' Compensation Board",
        "agency_filter": "Kansas City Workers' Compensation Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider099",
        "name": "kancit_099",
        "agency": "Kansas City Young Adult City Council",
        "agency_filter": "Kansas City Young Adult City Council",
        "classification": CITY_COUNCIL,
    },
    {
        "class_name": "KancitSpider100",
        "name": "kancit_100",
        "agency": "Kansas City, Missouri Homesteading Authority",
        "agency_filter": "Kansas City, Missouri Homesteading Authority",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider101",
        "name": "kancit_101",
        "agency": "KC Downtown Streetcar Transportation Development District",
        "agency_filter": "KC Downtown Streetcar Transportation Development District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider102",
        "name": "kancit_102",
        "agency": "KC Neighborhood Advisory Council",
        "agency_filter": "KC Neighborhood Advisory Council",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider103",
        "name": "kancit_103",
        "agency": "KC Parking and Transportation Commission",
        "agency_filter": "KC Parking and Transportation Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider104",
        "name": "kancit_104",
        "agency": "KC STAT",
        "agency_filter": "KC STAT",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider105",
        "name": "kancit_105",
        "agency": "KC Water Integrated Plan Advisory Committee",
        "agency_filter": "KC Water Integrated Plan Advisory Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider106",
        "name": "kancit_106",
        "agency": "KC Youth Commission",
        "agency_filter": "KC Youth Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider107",
        "name": "kancit_107",
        "agency": "KCATA",
        "agency_filter": "KCATA",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider108",
        "name": "kancit_108",
        "agency": "KCATA Funding Review Committee",
        "agency_filter": "KCATA Funding Review Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider109",
        "name": "kancit_109",
        "agency": "KCI Airport Community Improvement District Board",
        "agency_filter": "KCI Airport Community Improvement District Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider110",
        "name": "kancit_110",
        "agency": "KCTGA Comprehensive HIV Prevention & Care Plan",
        "agency_filter": "KCTGA Comprehensive HIV Prevention & Care Plan",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider111",
        "name": "kancit_111",
        "agency": "Land Bank Agency",
        "agency_filter": "Land Bank Agency",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider112",
        "name": "kancit_112",
        "agency": "Land Bank Board of Commissioners",
        "agency_filter": "Land Bank Board of Commissioners",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider113",
        "name": "kancit_113",
        "agency": "Landmarks Historic Trust Corporation",
        "agency_filter": "Landmarks Historic Trust Corporation",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider114",
        "name": "kancit_114",
        "agency": "Legal Review Committee",
        "agency_filter": "Legal Review Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider115",
        "name": "kancit_115",
        "agency": "Legislative Committee",
        "agency_filter": "Legislative Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider116",
        "name": "kancit_116",
        "agency": "Legislative, Rules and Ethics Committee",
        "agency_filter": "Legislative, Rules and Ethics Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider117",
        "name": "kancit_117",
        "agency": "LGBTQ Commission",
        "agency_filter": "LGBTQ Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider118",
        "name": "kancit_118",
        "agency": "Lien Waiver Committee",
        "agency_filter": "Lien Waiver Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider119",
        "name": "kancit_119",
        "agency": "Linwood Shopping Center CID Board of Director's Meeting",
        "agency_filter": "Linwood Shopping Center CID Board of Director's Meeting",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider120",
        "name": "kancit_120",
        "agency": "Linwood Shopping Center Community Improvement District",
        "agency_filter": "Linwood Shopping Center Community Improvement District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider121",
        "name": "kancit_121",
        "agency": "Liquor Control Board of Review",
        "agency_filter": "Liquor Control Board of Review",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider122",
        "name": "kancit_122",
        "agency": "Main Street Rail Transportation Development District",
        "agency_filter": "Main Street Rail Transportation Development District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider123",
        "name": "kancit_123",
        "agency": "Mayor's Commission for New Americans",
        "agency_filter": "Mayor's Commission for New Americans",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider124",
        "name": "kancit_124",
        "agency": "Mayor's Commission on Reparations Committee",
        "agency_filter": "Mayor's Commission on Reparations Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider125",
        "name": "kancit_125",
        "agency": "Mayor's New Tools Task Force Board",
        "agency_filter": "Mayor's New Tools Task Force Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider126",
        "name": "kancit_126",
        "agency": "Metro North Crossing Community Improvement District",
        "agency_filter": "Metro North Crossing Community Improvement District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider127",
        "name": "kancit_127",
        "agency": "Midtown Housing Advisory Board",
        "agency_filter": "Midtown Housing Advisory Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider128",
        "name": "kancit_128",
        "agency": "Municipal Art Commission",
        "agency_filter": "Municipal Art Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider129",
        "name": "kancit_129",
        "agency": "Municipal Judicial Nominating Commission",
        "agency_filter": "Municipal Judicial Nominating Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider130",
        "name": "kancit_130",
        "agency": "Municipal Officials and Officers Ethics Commission",
        "agency_filter": "Municipal Officials and Officers Ethics Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider131",
        "name": "kancit_131",
        "agency": "Neighborhood and Housing Joint Committee",
        "agency_filter": "Neighborhood and Housing Joint Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider132",
        "name": "kancit_132",
        "agency": "Neighborhood Development and Housing Committee",
        "agency_filter": "Neighborhood Development and Housing Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider133",
        "name": "kancit_133",
        "agency": "Neighborhood Development Committee",
        "agency_filter": "Neighborhood Development Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider134",
        "name": "kancit_134",
        "agency": "Neighborhood Planning and Development Committee",
        "agency_filter": "Neighborhood Planning and Development Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider135",
        "name": "kancit_135",
        "agency": "Neighborhood Program Advisory Committee",
        "agency_filter": "Neighborhood Program Advisory Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider136",
        "name": "kancit_136",
        "agency": "Neighborhood Tourist Development Fund",
        "agency_filter": "Neighborhood Tourist Development Fund",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider137",
        "name": "kancit_137",
        "agency": "Neighborhood Tourist Development Fund (NTDF)",
        "agency_filter": "Neighborhood Tourist Development Fund (NTDF)",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider138",
        "name": "kancit_138",
        "agency": "Neighborhoods and Public Safety & Housing Joint Committee",
        "agency_filter": "Neighborhoods and Public Safety & Housing Joint Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider139",
        "name": "kancit_139",
        "agency": "Neighborhoods and Public Safety Committee",
        "agency_filter": "Neighborhoods and Public Safety Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider140",
        "name": "kancit_140",
        "agency": "Neighborhoods, Housing & Healthy Communities Committee",
        "agency_filter": "Neighborhoods, Housing & Healthy Communities Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider141",
        "name": "kancit_141",
        "agency": "Northland Gateway Community Improvement District",
        "agency_filter": "Northland Gateway Community Improvement District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider142",
        "name": "kancit_142",
        "agency": "NPD and Special Committee on Housing Policy Committee",
        "agency_filter": "NPD and Special Committee on Housing Policy Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider143",
        "name": "kancit_143",
        "agency": "Operations And Aviation",
        "agency_filter": "Operations And Aviation",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider144",
        "name": "kancit_144",
        "agency": "Operations Committee",
        "agency_filter": "Operations Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider145",
        "name": "kancit_145",
        "agency": "Parking and Transportation Commission",
        "agency_filter": "Parking and Transportation Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider146",
        "name": "kancit_146",
        "agency": "Parking Policy Review Board",
        "agency_filter": "Parking Policy Review Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider147",
        "name": "kancit_147",
        "agency": "Parks & Recreation Board of Commissioners",
        "agency_filter": "Parks & Recreation Board of Commissioners",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider148",
        "name": "kancit_148",
        "agency": "Parks and Recreation Board of Commissioners",
        "agency_filter": "Parks and Recreation Board of Commissioners",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider149",
        "name": "kancit_149",
        "agency": "Partners for Peace",
        "agency_filter": "Partners for Peace",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider150",
        "name": "kancit_150",
        "agency": "Pension Reform Task Force Committee",
        "agency_filter": "Pension Reform Task Force Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider151",
        "name": "kancit_151",
        "agency": "Planning and Zoning Committee",
        "agency_filter": "Planning and Zoning Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider152",
        "name": "kancit_152",
        "agency": "Planning Zoning and Economic Development Committee and Neighborhoods and Public Safety Committee Joint Session",
        "agency_filter": "Planning Zoning and Economic Development Committee and Neighborhoods and Public Safety Committee Joint Session",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider153",
        "name": "kancit_153",
        "agency": "Planning, Zoning & Economic Development Committee",
        "agency_filter": "Planning, Zoning & Economic Development Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider154",
        "name": "kancit_154",
        "agency": "Planning, Zoning and Economic Development -Finance, Governance and Ethics Committee",
        "agency_filter": "Planning, Zoning and Economic Development -Finance, Governance and Ethics Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider155",
        "name": "kancit_155",
        "agency": "Port KC",
        "agency_filter": "Port KC",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider156",
        "name": "kancit_156",
        "agency": "Property Maintenance Appeals Board",
        "agency_filter": "Property Maintenance Appeals Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider157",
        "name": "kancit_157",
        "agency": "Public Budget Hearings",
        "agency_filter": "Public Budget Hearings",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider158",
        "name": "kancit_158",
        "agency": "Public Hearing on Mast",
        "agency_filter": "Public Hearing on Mast",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider159",
        "name": "kancit_159",
        "agency": "Public Hearing on Storm Sewer Construction Regulations and Material Specifications",
        "agency_filter": "Public Hearing on Storm Sewer Construction Regulations and Material Specifications",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider160",
        "name": "kancit_160",
        "agency": "Public Improvement Advisory Committee",
        "agency_filter": "Public Improvement Advisory Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider161",
        "name": "kancit_161",
        "agency": "Public Improvement Advisory Committee (PIAC)",
        "agency_filter": "Public Improvement Advisory Committee (PIAC)",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider162",
        "name": "kancit_162",
        "agency": "Public Safety & Emergency Services Committee",
        "agency_filter": "Public Safety & Emergency Services Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider163",
        "name": "kancit_163",
        "agency": "Public Safety and Neighborhoods Committee",
        "agency_filter": "Public Safety and Neighborhoods Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider164",
        "name": "kancit_164",
        "agency": "Public Safety Group",
        "agency_filter": "Public Safety Group",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider165",
        "name": "kancit_165",
        "agency": "PZE and Transportation Joint Comittee",
        "agency_filter": "PZE and Transportation Joint Comittee",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider166",
        "name": "kancit_166",
        "agency": "PZE Committee Worksession",
        "agency_filter": "PZE Committee Worksession",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider167",
        "name": "kancit_167",
        "agency": "Redistricting Advisory Board",
        "agency_filter": "Redistricting Advisory Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider168",
        "name": "kancit_168",
        "agency": "Risk Management Committee",
        "agency_filter": "Risk Management Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider169",
        "name": "kancit_169",
        "agency": "Rules And Audit Committee",
        "agency_filter": "Rules And Audit Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider170",
        "name": "kancit_170",
        "agency": "Sav KC",
        "agency_filter": "Sav KC",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider171",
        "name": "kancit_171",
        "agency": "Senior Citizens' Advisory Council",
        "agency_filter": "Senior Citizens' Advisory Council",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider172",
        "name": "kancit_172",
        "agency": "Service First Meetings",
        "agency_filter": "Service First Meetings",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider173",
        "name": "kancit_173",
        "agency": "Small Business Task Force (SMBTF)",
        "agency_filter": "Small Business Task Force (SMBTF)",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider174",
        "name": "kancit_174",
        "agency": "Small Business, Entrepreneurship & Jobs Committee",
        "agency_filter": "Small Business, Entrepreneurship & Jobs Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider175",
        "name": "kancit_175",
        "agency": "Special Committee for Emergency Services",
        "agency_filter": "Special Committee for Emergency Services",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider176",
        "name": "kancit_176",
        "agency": "Special Committee for Legal Review",
        "agency_filter": "Special Committee for Legal Review",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider177",
        "name": "kancit_177",
        "agency": "Special Committee for Municipal Rehabilitation and Detention",
        "agency_filter": "Special Committee for Municipal Rehabilitation and Detention",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider178",
        "name": "kancit_178",
        "agency": "Special Committee on Housing Policy",
        "agency_filter": "Special Committee on Housing Policy",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider179",
        "name": "kancit_179",
        "agency": "Special Committee on Small Businesses",
        "agency_filter": "Special Committee on Small Businesses",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider180",
        "name": "kancit_180",
        "agency": "Special Redistricting Committee",
        "agency_filter": "Special Redistricting Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider181",
        "name": "kancit_181",
        "agency": "Strategic Planning Session",
        "agency_filter": "Strategic Planning Session",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider182",
        "name": "kancit_182",
        "agency": "Tax Increment Financing Commission",
        "agency_filter": "Tax Increment Financing Commission",
        "classification": COMMISSION,
    },
    {
        "class_name": "KancitSpider183",
        "name": "kancit_183",
        "agency": "Tenant's Right to Counsel",
        "agency_filter": "Tenant's Right to Counsel",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider184",
        "name": "kancit_184",
        "agency": "The Antioch Center Community Improvement District",
        "agency_filter": "The Antioch Center Community Improvement District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider185",
        "name": "kancit_185",
        "agency": "Transportation & Infrastructure Committee",
        "agency_filter": "Transportation & Infrastructure Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider186",
        "name": "kancit_186",
        "agency": "Transportation and Infrastructure & Planning, Zoning and Development Joint Committee",
        "agency_filter": "Transportation and Infrastructure & Planning, Zoning and Development Joint Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider187",
        "name": "kancit_187",
        "agency": "Transportation and Infrastructure Committee",
        "agency_filter": "Transportation and Infrastructure Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider188",
        "name": "kancit_188",
        "agency": "Transportation and Infrastructure Committee Worksession",
        "agency_filter": "Transportation and Infrastructure Committee Worksession",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider189",
        "name": "kancit_189",
        "agency": "Transportation and Infrastructure Worksession",
        "agency_filter": "Transportation and Infrastructure Worksession",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider190",
        "name": "kancit_190",
        "agency": "Transportation, Infrastructure and Operations Committee",
        "agency_filter": "Transportation, Infrastructure and Operations Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider191",
        "name": "kancit_191",
        "agency": "Vine Street Community Improvement District",
        "agency_filter": "Vine Street Community Improvement District",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider192",
        "name": "kancit_192",
        "agency": "Violence Free KC Committee",
        "agency_filter": "Violence Free KC Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider193",
        "name": "kancit_193",
        "agency": "Violence Free KC Committee (VFKCC)",
        "agency_filter": "Violence Free KC Committee (VFKCC)",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider194",
        "name": "kancit_194",
        "agency": "Vision Zero Task Force",
        "agency_filter": "Vision Zero Task Force",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider195",
        "name": "kancit_195",
        "agency": "VisitKC",
        "agency_filter": "VisitKC",
        "classification": NOT_CLASSIFIED,
    },
    {
        "class_name": "KancitSpider196",
        "name": "kancit_196",
        "agency": "Water Utilities Advisory Board",
        "agency_filter": "Water Utilities Advisory Board",
        "classification": BOARD,
    },
    {
        "class_name": "KancitSpider197",
        "name": "kancit_197",
        "agency": "Westport Events Management Committee",
        "agency_filter": "Westport Events Management Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider198",
        "name": "kancit_198",
        "agency": "Worksession of the Finance & Audit Committee",
        "agency_filter": "Worksession of the Finance & Audit Committee",
        "classification": COMMITTEE,
    },
    {
        "class_name": "KancitSpider199",
        "name": "kancit_199",
        "agency": "Youth Development Committee",
        "agency_filter": "Youth Development Committee",
        "classification": COMMITTEE,
    },
]


def create_spiders():
    """
    Dynamically create spider classes using the spider_configs list
    and register them in the global namespace.
    """
    for config in spider_configs:
        class_name = config["class_name"]

        if class_name not in globals():
            # Build attributes dict without class_name
            attrs = {k: v for k, v in config.items() if k != "class_name"}

            # Dynamically create the spider class
            spider_class = type(
                class_name,
                (KancitMissouricityMixin,),
                attrs,
            )

            # Register the class in the global namespace
            globals()[class_name] = spider_class


# Create all spider classes at module load
create_spiders()
